package ace

import("strconv";"strings")

type synthesisError string
func(e synthesisError)Error()string{return string(e)}

func AdaptiveUniversalSynthesis(c ArchitectureCandidate,s CapabilitySpecification)(ModificationProposal,error){if len(s.KnownExamples)<2||len(s.Inputs)==0||len(s.Outputs)==0{return ModificationProposal{},synthesisError("insufficient behavioral evidence")};vars:=append([]string(nil),s.Inputs...);exprs:=adaptiveExpressions(vars,observedConstants(s.KnownExamples),s.KnownExamples,3,2500);out:=s.Outputs[0];for _,e:=range exprs{p:=UniversalProgram{Statements:[]UStmt{{Kind:"assign",Target:out,Expr:cloneExpr(e)}}};if programFits(p,s.KnownExamples){return encodeUniversal(p,s,c)}};target:=make([]string,len(s.KnownExamples));for i,tc:=range s.KnownExamples{target[i]=tc.Expected[out]};type ie struct{e UExpr;v []string};indexed:=make([]ie,0,len(exprs));for _,e:=range exprs{v:=make([]string,len(s.KnownExamples));ok:=true;for i,tc:=range s.KnownExamples{x,_,err:=e.eval(tc.Input);if err!=nil{ok=false;break};v[i]=strconv.Itoa(x)};if ok{indexed=append(indexed,ie{e,v})}};for _,v:=range vars{for _,rhs:=range exprs{for _,cmp:=range []string{"eq","lt"}{mask:=make([]bool,len(s.KnownExamples));valid:=true;for i,tc:=range s.KnownExamples{a,_,ea:=UExpr{Kind:"var",Value:v}.eval(tc.Input);b,_,eb:=rhs.eval(tc.Input);if ea!=nil||eb!=nil{valid=false;break};if cmp=="eq"{mask[i]=a==b}else{mask[i]=a<b}};if !valid{continue};at,af:=true,true;for _,m:=range mask{at=at&&m;af=af&&!m};if at||af{continue};for _,te:=range indexed{good:=true;for i:=range target{if mask[i]&&te.v[i]!=target[i]{good=false;break}};if !good{continue};for _,ee:=range indexed{ok:=true;for i:=range target{if !mask[i]&&ee.v[i]!=target[i]{ok=false;break}};if ok{cond:=UExpr{Kind:cmp,Left:&UExpr{Kind:"var",Value:v},Right:cloneExpr(rhs)};p:=UniversalProgram{Statements:[]UStmt{{Kind:"if",Cond:&cond,Then:[]UStmt{{Kind:"assign",Target:out,Expr:cloneExpr(te.e)}},Else:[]UStmt{{Kind:"assign",Target:out,Expr:cloneExpr(ee.e)}}}}};if programFits(p,s.KnownExamples){return encodeUniversal(p,s,c)}}}}}}};return ModificationProposal{},synthesisError("adaptive universal synthesis exhausted search space")}

func observedConstants(cs []ProgramTestCase)[]int{set:=map[int]bool{-2:true,-1:true,0:true,1:true,2:true};for _,tc:=range cs{for _,r:=range tc.Input{if n,e:=strconv.Atoi(r);e==nil{set[n]=true}};for _,r:=range tc.Expected{if n,e:=strconv.Atoi(r);e==nil{set[n]=true}}};o:=make([]int,0,len(set));for n:=range set{o=append(o,n)};for i:=1;i<len(o);i++{for j:=i;j>0&&o[j]<o[j-1];j--{o[j],o[j-1]=o[j-1],o[j]}};return o}
func adaptiveExpressions(vars []string,cs []int,cases []ProgramTestCase,maxDepth,maxClasses int)[]UExpr{front:=make([]UExpr,0,len(vars)+len(cs));for _,v:=range vars{front=append(front,UExpr{Kind:"var",Value:v})};for _,n:=range cs{front=append(front,UExpr{Kind:"const",Value:strconv.Itoa(n)})};seen:=map[string]bool{};for _,e:=range front{seen[exprSemanticSignature(e,cases)]=true};levels:=[][]UExpr{append([]UExpr(nil),front...)};for d:=1;d<=maxDepth&&len(front)<maxClasses;d++{prev:=levels[len(levels)-1];next:=make([]UExpr,0);for _,a:=range prev{for _,b:=range prev{for _,k:=range []string{"add","sub","mul"}{e:=UExpr{Kind:k,Left:cloneExpr(a),Right:cloneExpr(b)};sig:=exprSemanticSignature(e,cases);if !seen[sig]{seen[sig]=true;next=append(next,e)};if len(front)+len(next)>=maxClasses{break}};if len(front)+len(next)>=maxClasses{break}};if len(front)+len(next)>=maxClasses{break}};front=append(front,next...);levels=append(levels,next);if len(next)==0{break}};return front}
func exprSemanticSignature(e UExpr,cs []ProgramTestCase)string{var b strings.Builder;for _,tc:=range cs{v,_,err:=e.eval(tc.Input);if err!=nil{b.WriteString("!")}else{b.WriteString(strconv.Itoa(v));b.WriteByte(',')}};return b.String()}
