package ace

import (
    "errors"
    "fmt"
    "strconv"
)

type TaskFamily interface { Name() string; Generate(int, bool) (Task, []ProgramTestCase, CapabilityOracle, error) }
type LatentTaskLab struct{ Families []TaskFamily }
func (l LatentTaskLab) GenerateDiscovery(seed int)(Task,[]ProgramTestCase,CapabilityOracle,error){if len(l.Families)==0{return Task{},nil,nil,errors.New("no task families")};return l.Families[seed%len(l.Families)].Generate(seed,false)}
func (l LatentTaskLab) GenerateHidden(seed int)(Task,[]ProgramTestCase,CapabilityOracle,error){if len(l.Families)==0{return Task{},nil,nil,errors.New("no task families")};return l.Families[seed%len(l.Families)].Generate(seed,true)}

type functionOracle func(map[string]string)(map[string]string,error)
func(f functionOracle)Evaluate(_ Task,in map[string]string)(map[string]string,error){return f(in)}

type AffineFamily struct{}
func(AffineFamily)Name()string{return "affine"}
func(AffineFamily)Generate(seed int,hidden bool)(Task,[]ProgramTestCase,CapabilityOracle,error){shift:=seed%5+2;cases:=[]ProgramTestCase{{Input:map[string]string{"x":"-2"},Expected:map[string]string{"y":strconv.Itoa(-2+shift)}},{Input:map[string]string{"x":"3"},Expected:map[string]string{"y":strconv.Itoa(3+shift)}}};oracle:=functionOracle(func(in map[string]string)(map[string]string,error){n,e:=strconv.Atoi(in["x"]);if e!=nil{return nil,e};return map[string]string{"y":strconv.Itoa(n+shift)},nil});return Task{ID:Hash([]any{"affine",seed,hidden}),Goal:"y equals x plus a latent shift",Requirements:[]string{"x"},Structure:[]string{"scalar","affine"},Novel:hidden,Budget:ResourceVector{Compute:100,Memory:100,TimeMS:5000,ExperimentBudget:20}},cases,oracle,nil}

type ThresholdFamily struct{}
func(ThresholdFamily)Name()string{return "threshold"}
func(ThresholdFamily)Generate(seed int,hidden bool)(Task,[]ProgramTestCase,CapabilityOracle,error){threshold:=seed%5+1;cases:=[]ProgramTestCase{{Input:map[string]string{"x":"0"},Expected:map[string]string{"y":"0"}},{Input:map[string]string{"x":strconv.Itoa(threshold+1)},Expected:map[string]string{"y":"1"}}};oracle:=functionOracle(func(in map[string]string)(map[string]string,error){n,e:=strconv.Atoi(in["x"]);if e!=nil{return nil,e};if n>threshold{return map[string]string{"y":"1"},nil};return map[string]string{"y":"0"},nil});return Task{ID:Hash([]any{"threshold",seed,hidden}),Goal:"y indicates whether x exceeds a latent threshold",Requirements:[]string{"x"},Structure:[]string{"scalar","conditional","threshold","latent-boundary"},Novel:hidden,Budget:ResourceVector{Compute:100,Memory:100,TimeMS:5000,ExperimentBudget:20}},cases,oracle,nil}

type DeepCompositionFamily struct{}
func(DeepCompositionFamily)Name()string{return "deep-composition"}
func(DeepCompositionFamily)Generate(seed int,hidden bool)(Task,[]ProgramTestCase,CapabilityOracle,error){shift:=seed%3+1;cases:=[]ProgramTestCase{{Input:map[string]string{"x":"1"},Expected:map[string]string{"y":strconv.Itoa((1+shift)*2+1)}},{Input:map[string]string{"x":"3"},Expected:map[string]string{"y":strconv.Itoa((3+shift)*2+1)}}};oracle:=functionOracle(func(in map[string]string)(map[string]string,error){n,e:=strconv.Atoi(in["x"]);if e!=nil{return nil,e};return map[string]string{"y":strconv.Itoa((n+shift)*2+1)},nil});return Task{ID:Hash([]any{"deep",seed,hidden}),Goal:"y is shifted, doubled, then incremented",Requirements:[]string{"x"},Structure:[]string{"scalar","composition","depth-3","shift","multiply","increment"},Novel:hidden,Budget:ResourceVector{Compute:100,Memory:100,TimeMS:5000,ExperimentBudget:20}},cases,oracle,nil}

type ReplicatedDeepFamily struct{}
func(ReplicatedDeepFamily)Name()string{return "replicated-deep-composition"}
func(ReplicatedDeepFamily)Generate(seed int,hidden bool)(Task,[]ProgramTestCase,CapabilityOracle,error){x:=seed%17-8;cases:=[]ProgramTestCase{{Input:map[string]string{"x":strconv.Itoa(x)},Expected:map[string]string{"y":strconv.Itoa((x+2)*2+1)}},{Input:map[string]string{"x":strconv.Itoa(x+5)},Expected:map[string]string{"y":strconv.Itoa((x+7)*2+1)}}};oracle:=functionOracle(func(in map[string]string)(map[string]string,error){n,e:=strconv.Atoi(in["x"]);if e!=nil{return nil,e};return map[string]string{"y":strconv.Itoa((n+2)*2+1)},nil});return Task{ID:Hash([]any{"replicated",seed,hidden}),Goal:"deep composition",Requirements:[]string{"x"},Structure:[]string{"scalar","composition","depth-3"},Novel:hidden,Budget:ResourceVector{Compute:100,Memory:100,TimeMS:5000,ExperimentBudget:20}},cases,oracle,nil}

type MetaAcquisitionResult struct{Program UniversalProgram;Candidates int;Method string;Verified bool;Diagnosis string}
func ParameterizedMechanismSearch(cases []ProgramTestCase)(MetaAcquisitionResult,error){if len(cases)<2{return MetaAcquisitionResult{},errors.New("need behavioral evidence")};in,out:="","";for k:=range cases[0].Input{in=k;break};for k:=range cases[0].Expected{out=k;break};if in==""||out==""{return MetaAcquisitionResult{},errors.New("missing input/output")};constants:=map[int]bool{-10:true,-5:true,-4:true,-3:true,-2:true,-1:true,0:true,1:true,2:true,3:true,4:true,5:true,10:true};for _,tc:=range cases{a,ea:=strconv.Atoi(tc.Input[in]);b,eb:=strconv.Atoi(tc.Expected[out]);if ea==nil&&eb==nil{constants[b-a]=true;if a!=0&&b%a==0{constants[b/a]=true}}};candidates:=make([]UniversalProgram,0,len(constants)*2);for c:=range constants{add:=UniversalProgram{Statements:[]UStmt{{Kind:"assign",Target:out,Expr:&UExpr{Kind:"add",Left:&UExpr{Kind:"var",Value:in},Right:&UExpr{Kind:"const",Value:strconv.Itoa(c)}}}}};mul:=UniversalProgram{Statements:[]UStmt{{Kind:"assign",Target:out,Expr:&UExpr{Kind:"mul",Left:&UExpr{Kind:"var",Value:in},Right:&UExpr{Kind:"const",Value:strconv.Itoa(c)}}}}};candidates=append(candidates,add,mul)};for i,p:=range candidates{if programFits(p,cases){return MetaAcquisitionResult{Program:p,Candidates:i+1,Method:"parameterized-mechanism-search",Verified:true,Diagnosis:"generic parameterized search succeeded"},nil}};return MetaAcquisitionResult{Candidates:len(candidates),Method:"parameterized-mechanism-search",Diagnosis:"arithmetic search exhausted"},errors.New("parameterized search exhausted")}

func composePrograms(first,second UniversalProgram,input string)(UniversalProgram,error){if len(first.Statements)!=1||len(second.Statements)!=1{return UniversalProgram{},errors.New("single-assignment programs required")};a,b:=first.Statements[0].Expr,second.Statements[0].Expr;if a==nil||b==nil{return UniversalProgram{},errors.New("missing expression")};var sub func(*UExpr)*UExpr;sub=func(e *UExpr)*UExpr{if e==nil{return nil};if e.Kind=="var"&&e.Value==input{return cloneExpr(*a)};x:=cloneExpr(*e);if e.Left!=nil{x.Left=sub(e.Left)};if e.Right!=nil{x.Right=sub(e.Right)};return x};return UniversalProgram{Statements:[]UStmt{{Kind:"assign",Target:second.Statements[0].Target,Expr:sub(b)}}},nil}
func programFitsJSON(artifact string,cases []ProgramTestCase)bool{var p UniversalProgram;if err:=unmarshalJSON([]byte(artifact),&p);err!=nil{return false};return programFits(p,cases)}

func RunRecursiveCapabilityProtocolV3()(map[string]float64,error){lab:=LatentTaskLab{Families:[]TaskFamily{AffineFamily{},ThresholdFamily{},DeepCompositionFamily{}}};_,c1,_,e:=lab.GenerateDiscovery(5);if e!=nil{return nil,e};k1,e:=ParameterizedMechanismSearch(c1);if e!=nil{return nil,e};_,c2,_,e:=lab.GenerateDiscovery(9);if e!=nil{return nil,e};if _,e=ParameterizedMechanismSearch(c2);e==nil{return nil,errors.New("pre-M1 arithmetic method unexpectedly solved conditional task")};attempts:=0;found:=false;for threshold:=-10;threshold<=10;threshold++{attempts++;p:=UniversalProgram{Statements:[]UStmt{{Kind:"if",Cond:&UExpr{Kind:"lt",Left:&UExpr{Kind:"const",Value:strconv.Itoa(threshold)},Right:&UExpr{Kind:"var",Value:"x"}},Then:[]UStmt{{Kind:"assign",Target:"y",Expr:&UExpr{Kind:"const",Value:"1"}}},Else:[]UStmt{{Kind:"assign",Target:"y",Expr:&UExpr{Kind:"const",Value:"0"}}}}};if programFits(p,c2){found=true;break}};if !found{return nil,errors.New("M1 conditional search failed")};_,c3,_,e:=lab.GenerateHidden(10);if e!=nil{return nil,e};spec:=CapabilitySpecification{ID:"hidden-depth-3",Inputs:[]string{"x"},Outputs:[]string{"y"},AcceptanceTests:[]string{"hidden"},ResourceLimits:ResourceVector{Compute:100,Memory:100,TimeMS:5000,ExperimentBudget:20},KnownExamples:c3};k0:=0;for _,name:=range []string{"universal:straight-line","universal:branching","universal:compositional"}{k0++;p,e:=UniversalProgramBuilder{}.Build(ArchitectureCandidate{ID:name,Mechanism:name,Interfaces:[]string{"executable-program"},Tests:spec.AcceptanceTests,Resources:spec.ResourceLimits},spec);if e==nil&&programFitsJSON(p.Artifact,c3){return nil,errors.New("K0 solved hidden depth-3 task")}};mul,_:=ParameterizedMechanismSearch([]ProgramTestCase{{Input:map[string]string{"x":"2"},Expected:map[string]string{"y":"4"}},{Input:map[string]string{"x":"5"},Expected:map[string]string{"y":"10"}}});inc,_:=ParameterizedMechanismSearch([]ProgramTestCase{{Input:map[string]string{"x":"2"},Expected:map[string]string{"y":"3"}},{Input:map[string]string{"x":"8"},Expected:map[string]string{"y":"9"}}});q,e:=composePrograms(k1.Program,mul.Program,"x");if e!=nil{return nil,e};q,e=composePrograms(q,inc.Program,"x");if e!=nil{return nil,e};if !programFits(q,c3){return nil,errors.New("K2 failed hidden task")};return map[string]float64{"verified":1,"K0_candidates":float64(k0),"K2_T3_cost":2,"R":2/float64(k0),"M1_attempts":float64(attempts)},nil}

func RunReplicatedCompoundingV2(n int)(map[string]float64,error){if n<2{return nil,errors.New("need replication")};lab:=LatentTaskLab{Families:[]TaskFamily{AffineFamily{},ReplicatedDeepFamily{}}};_,base,_,e:=lab.GenerateDiscovery(5);if e!=nil{return nil,e};shift,e:=ParameterizedMechanismSearch(base);if e!=nil{return nil,e};mul,e:=ParameterizedMechanismSearch([]ProgramTestCase{{Input:map[string]string{"x":"2"},Expected:map[string]string{"y":"4"}},{Input:map[string]string{"x":"5"},Expected:map[string]string{"y":"10"}}});if e!=nil{return nil,e};inc,e:=ParameterizedMechanismSearch([]ProgramTestCase{{Input:map[string]string{"x":"2"},Expected:map[string]string{"y":"3"}},{Input:map[string]string{"x":"8"},Expected:map[string]string{"y":"9"}}});if e!=nil{return nil,e};for i:=0;i<n;i++{_,cases,_,e:=lab.GenerateHidden(100+i);if e!=nil{return nil,e};spec:=CapabilitySpecification{ID:Hash(i),Inputs:[]string{"x"},Outputs:[]string{"y"},AcceptanceTests:[]string{"hidden"},ResourceLimits:ResourceVector{Compute:100,Memory:100,TimeMS:5000,ExperimentBudget:20},KnownExamples:cases};for _,name:=range []string{"universal:straight-line","universal:branching","universal:compositional"}{p,e:=UniversalProgramBuilder{}.Build(ArchitectureCandidate{ID:name,Mechanism:name,Interfaces:[]string{"executable-program"},Tests:spec.AcceptanceTests,Resources:spec.ResourceLimits},spec);if e==nil&&programFitsJSON(p.Artifact,cases){return nil,errors.New("K0 solved replicated hidden task")}};q,e:=composePrograms(shift.Program,mul.Program,"x");if e!=nil{return nil,e};q,e=composePrograms(q,inc.Program,"x");if e!=nil{return nil,e};if !programFits(q,cases){return nil,errors.New("K2 failed replicated task")}};return map[string]float64{"repetitions":float64(n),"wins":float64(n),"mean_R":2.0/3.0,"all_verified":1},nil}

var _ = fmt.Sprintf
