package ace

import("encoding/json";"errors";"fmt";"sort";"strconv")
type CapabilityOracle interface{Evaluate(Task,map[string]string)(map[string]string,error)}
type Counterexample struct{Input map[string]string;Expected map[string]string;Kind string;Reason string}
type CounterexampleGenerator interface{Generate(Task,CapabilitySpecification,CapabilityOracle,[]map[string]string)([]Counterexample,error)}
type IndependentCounterexampleGenerator struct{}
func(IndependentCounterexampleGenerator)Generate(t Task,s CapabilitySpecification,oracle CapabilityOracle,seeds []map[string]string)([]Counterexample,error){if oracle==nil{return nil,errors.New("counterexample generation requires an independent oracle")};inputs:=make([]map[string]string,0,len(seeds)*4);for _,in:=range seeds{inputs=append(inputs,cloneMap(in));for k,v:=range in{n,err:=strconv.Atoi(v);if err!=nil{continue};for _,d:=range []int{-1,1}{x:=cloneMap(in);x[k]=strconv.Itoa(n+d);inputs=append(inputs,x)}}};seen:=map[string]bool{};out:=make([]Counterexample,0,len(inputs));for _,in:=range inputs{expected,err:=oracle.Evaluate(t,in);if err!=nil{return nil,err};key:=Hash([]any{in,expected});if seen[key]{continue};seen[key]=true;out=append(out,Counterexample{Input:in,Expected:expected,Kind:"oracle-boundary",Reason:"independently generated evaluation case"})};return out,nil}
func cloneMap(in map[string]string)map[string]string{out:=make(map[string]string,len(in));for k,v:=range in{out[k]=v};return out}
func verifyUniversalArtifact(artifact string,cases []Counterexample)error{var p UniversalProgram;if err:=json.Unmarshal([]byte(artifact),&p);err!=nil{return err};for _,c:=range cases{got,err:=p.Run(c.Input);if err!=nil{return err};for k,v:=range c.Expected{if got[k]!=v{return fmt.Errorf("counterexample %s: output %s=%q want %q",c.Kind,k,got[k],v)}}};return nil}
func firstCounterexample(artifact string,cases []Counterexample)(*Counterexample,error){var p UniversalProgram;if err:=json.Unmarshal([]byte(artifact),&p);err!=nil{return nil,err};for i:=range cases{c:=cases[i];got,err:=p.Run(c.Input);if err!=nil{return &c,nil};for k,v:=range c.Expected{if got[k]!=v{return &c,nil}}};return nil,nil}
type AcquisitionExperience struct{TaskStructure string;Method string;SearchAttempts int;Cost ResourceVector;Verified bool;TransferScore float64;Failure string;Provenance Provenance}
type AcquisitionMethodPolicy struct{History []AcquisitionExperience}
func(p AcquisitionMethodPolicy)Rank(methods []ArchitectureCandidate,structure string)[]ArchitectureCandidate{score:=map[string]float64{};for _,h:=range p.History{if h.TaskStructure!=structure{continue};if h.Verified{score[h.Method]+=1/float64(h.SearchAttempts+1)}else{score[h.Method]-=.25}};out:=append([]ArchitectureCandidate(nil),methods...);sort.SliceStable(out,func(i,j int)bool{return score[out[i].Mechanism]>score[out[j].Mechanism]});return out}
type CapabilityLibrary struct{Records []CapabilityRecord;Methods []AcquisitionExperience}
func(l *CapabilityLibrary)Add(rec CapabilityRecord,exp AcquisitionExperience)error{if rec.Artifact==""||rec.Capability.ID==""{return errors.New("library rejects unverified or empty capability")};for _,r:=range l.Records{if r.Capability.ID==rec.Capability.ID{return nil}};l.Records=append(l.Records,rec);l.Methods=append(l.Methods,exp);return nil}
func(l CapabilityLibrary)Search(structure string)[]CapabilityRecord{out:=make([]CapabilityRecord,0);for _,r:=range l.Records{if r.Capability.Strength>0{out=append(out,r)}};return out}
type GeneralAcquisitionEngine struct{Search UniversalMechanismSearch;Builder UniversalProgramBuilder;Counterexamples CounterexampleGenerator;Oracle CapabilityOracle;Library CapabilityLibrary;Policy AcquisitionMethodPolicy}
type AcquisitionResult struct{Record CapabilityRecord;Verification VerificationResult;Experience AcquisitionExperience;Counterexamples []Counterexample}
func(e *GeneralAcquisitionEngine)Acquire(t Task,spec CapabilitySpecification,seeds []map[string]string)(AcquisitionResult,error){if e.Oracle==nil||e.Counterexamples==nil{return AcquisitionResult{},errors.New("general acquisition requires independent evaluation")};candidates,err:=e.Search.SearchMechanisms(spec,t.Budget);if err!=nil{return AcquisitionResult{},err};structure:=Hash([]any{spec.Inputs,spec.Outputs,spec.Invariants});candidates=e.Policy.Rank(candidates,structure);cases,err:=e.Counterexamples.Generate(t,spec,e.Oracle,seeds);if err!=nil{return AcquisitionResult{},err};working:=append([]ProgramTestCase{},spec.KnownExamples...);const maxCEGISRounds=4;for i,c:=range candidates{for round:=0;round<maxCEGISRounds;round++{trial:=spec;trial.KnownExamples=working;p,err:=e.Builder.Build(c,trial);if err!=nil{break};bad,err:=firstCounterexample(p.Artifact,cases);if err!=nil{return AcquisitionResult{},err};if bad!=nil{if round+1==maxCEGISRounds{e.Policy.History=append(e.Policy.History,AcquisitionExperience{TaskStructure:structure,Method:c.Mechanism,SearchAttempts:i+1,Verified:false,Failure:"CEGIS budget exhausted"});break};working=append(working,ProgramTestCase{Input:cloneMap(bad.Input),Expected:cloneMap(bad.Expected)});continue};rec:=CapabilityRecord{Capability:Capability{ID:Hash([]any{"general-capability",spec.ID,c.Mechanism}),Name:spec.DesiredBehaviour,Strength:1,Version:1,KnownLimits:[]string{"current universal executable substrate"},Provenance:spec.Provenance},Artifact:p.Artifact,Tests:working,Mechanism:c.Mechanism,ArchitectureCost:float64(i+1)};exp:=AcquisitionExperience{TaskStructure:structure,Method:c.Mechanism,SearchAttempts:i+1,Cost:c.Resources,Verified:true,TransferScore:1,Provenance:Prov("general-acquisition",spec.ID,"verified",c)};if err:=e.Library.Add(rec,exp);err!=nil{return AcquisitionResult{},err};e.Policy.History=append(e.Policy.History,exp);return AcquisitionResult{Record:rec,Verification:VerificationResult{Status:"verified",Independent:true,Expected:spec.AcceptanceTests,Observed:[]string{"oracle-generated counterexamples passed","CEGIS repair loop converged"},Provenance:p.Provenance},Experience:exp,Counterexamples:cases},nil}};return AcquisitionResult{},errors.New("all general acquisition methods failed")}
