package ace

import("context";"errors";"fmt";"reflect";"sort";"strconv")
type AcquisitionMethodArtifact struct{ID string;Name string;DiagnosisTarget BottleneckClass;Preconditions []string;ExpectedStrengths []string;ExpectedFailureModes []string;InputCapability CapabilitySpecification;Procedure string;RepresentationPolicy string;CandidatePolicy string;VerificationPolicy string;Resources ResourceVector;Provenance Provenance;Dependencies []string;Performance MethodPerformance;RegressionConstraints []string;TransferEvidence []string;Artifact string}
type MethodPerformance struct{Attempts,Verified,Failures int;MeanCost,MeanGain float64;TransferWins,Generalization int}
type AcquisitionTelemetry struct{TaskID string;TaskStructure []string;KnownExamples,CandidateCount int;CandidateFailures []string;Counterexamples int;Representation []string;SearchPath []string;VerificationOutcomes []string;Cost ResourceVector}
type BottleneckClass string
const(BottleneckResource BottleneckClass="resource-insufficiency";BottleneckRepresentation BottleneckClass="representation-insufficiency";BottleneckSearchSpace BottleneckClass="search-space-insufficiency";BottleneckSearchOrder BottleneckClass="search-order-inefficiency";BottleneckDecomposition BottleneckClass="missing-decomposition";BottleneckAbstraction BottleneckClass="missing-reusable-abstraction";BottleneckVerification BottleneckClass="weak-verification";BottleneckCounterexample BottleneckClass="weak-counterexample-generation";BottleneckMethodChoice BottleneckClass="poor-method-selection";BottleneckUnknown BottleneckClass="unknown")
type BottleneckDiagnosis struct{Class BottleneckClass;Reason string;Confidence float64;Evidence []string}
type MethodCandidate struct{Artifact AcquisitionMethodArtifact;Score float64}
type MethodEvaluation struct{Candidate AcquisitionMethodArtifact;Verified bool;Gain float64;Cost ResourceVector;Transfer,Regression,LeakFree,FutureTraceChanged bool;Reason string}
func DiagnoseAcquisitionTelemetry(t AcquisitionTelemetry)BottleneckDiagnosis{if t.CandidateCount==0{return BottleneckDiagnosis{Class:BottleneckSearchSpace,Reason:"no candidates reached verification",Confidence:.95,Evidence:[]string{"candidate-count=0"}}};failed:=false;for _,f:=range t.CandidateFailures{if f!=""{failed=true;break}};if t.Counterexamples>0&&failed{return BottleneckDiagnosis{Class:BottleneckSearchSpace,Reason:"independent counterexamples rejected the available search family",Confidence:.85,Evidence:append([]string(nil),t.CandidateFailures...)}};if len(t.SearchPath)>t.CandidateCount*4{return BottleneckDiagnosis{Class:BottleneckSearchOrder,Reason:"search expanded substantially relative to candidates tested",Confidence:.7,Evidence:[]string{fmt.Sprintf("search-path=%d",len(t.SearchPath))}}};if len(t.Representation)==0{return BottleneckDiagnosis{Class:BottleneckRepresentation,Reason:"episode has no stable representation trace",Confidence:.65,Evidence:[]string{"representation-trace-empty"}}};if len(t.VerificationOutcomes)==0{return BottleneckDiagnosis{Class:BottleneckVerification,Reason:"no independent verification outcome was recorded",Confidence:.9,Evidence:[]string{"verification-trace-empty"}}};return BottleneckDiagnosis{Class:BottleneckUnknown,Reason:"telemetry does not discriminate a bottleneck",Confidence:.2}}
const defaultAcquisitionProcedureMaxSteps = 2

func AutonomousMethodCandidatesWithLibrary(d BottleneckDiagnosis,spec CapabilitySpecification,budget ResourceVector,lib *AbstractionLibrary)[]MethodCandidate {
	return AutonomousMethodCandidatesWithLibraryDepth(d,spec,budget,lib,defaultAcquisitionProcedureMaxSteps)
}

func AutonomousMethodCandidatesWithLibraryDepth(d BottleneckDiagnosis,spec CapabilitySpecification,budget ResourceVector,lib *AbstractionLibrary,maxSteps int)[]MethodCandidate{_ = d;procedures:=EnumerateAcquisitionProceduresWithLibrary(maxSteps,lib);out:=make([]MethodCandidate,0,len(procedures));marshalFailures:=0;for i,p:=range procedures{artifact,e:=p.Marshal();if e!=nil{marshalFailures++;fmt.Printf("ACQ_METHOD_FILTER index=%d stage=marshal depth=%d accepted=false reason=%q\n",i,len(p.Steps),e.Error());continue};sig:=procedureSignature(p);m:=AcquisitionMethodArtifact{ID:Hash([]any{"acquired-search-procedure",sig,spec.ID,d.Class}),Name:"acquired-procedure:"+sig,DiagnosisTarget:d.Class,Preconditions:[]string{"independent behavioral evidence","within resource budget"},ExpectedStrengths:[]string{"generic candidate-stream transformation"},ExpectedFailureModes:[]string{"insufficient behavioral evidence","resource exhaustion","no future trace effect"},InputCapability:spec,Procedure:artifact,RepresentationPolicy:"unchanged-unless-evidence-requires-revision",CandidatePolicy:"executable-procedure-enumeration",VerificationPolicy:"independent-heldout-regression-transfer",Resources:budget,Dependencies:abstractionDependencies(p),RegressionConstraints:[]string{"previous verified capabilities remain valid"},Provenance:Prov("blind-procedure-synthesis",spec.ID,"enumerate-generic-stream-program",p),Artifact:artifact};out=append(out,MethodCandidate{Artifact:m})};fmt.Printf("ACQ_METHOD_FILTER_SUMMARY generated=%d emitted=%d marshal_failures=%d\n",len(procedures),len(out),marshalFailures);return out}
func AutonomousMethodCandidates(d BottleneckDiagnosis,spec CapabilitySpecification,budget ResourceVector)[]MethodCandidate{return AutonomousMethodCandidatesWithLibrary(d,spec,budget,nil)}
func executeAcquisitionMethodWithLibrary(m AcquisitionMethodArtifact,spec CapabilitySpecification,lib *AbstractionLibrary)([]ArchitectureCandidate,error){p,e:=decodeAcquisitionProcedure(m.Artifact);if e!=nil{return nil,e};cs,e:=(UniversalMechanismSearch{}).SearchMechanisms(spec,spec.ResourceLimits);if e!=nil{return nil,e};return executeSearchProcedureWithLibrary(p,cs,lib)}
func executeAcquisitionMethod(m AcquisitionMethodArtifact,spec CapabilitySpecification)([]ArchitectureCandidate,error){return executeAcquisitionMethodWithLibrary(m,spec,nil)}
func sameMechanismOrder(a,b []ArchitectureCandidate)bool{if len(a)!=len(b){return false};for i:=range a{if a[i].Mechanism!=b[i].Mechanism{return false}};return true}
func sameCandidateState(a,b []ArchitectureCandidate)bool{return reflect.DeepEqual(a,b)}
func verifyMethodCandidateWithLibrary(m AcquisitionMethodArtifact,target CapabilitySpecification,hidden,baseline []ProgramTestCase,lib *AbstractionLibrary)MethodEvaluation{p,decodeErr:=decodeAcquisitionProcedure(m.Procedure);if decodeErr!=nil{fmt.Printf("ACQ_METHOD_VERIFY candidate=%s stage=decode depth=? accepted=false reason=%q\n",m.ID,decodeErr.Error());return MethodEvaluation{Candidate:m,Reason:decodeErr.Error()}};depth:=len(p.Steps);cs,e:=executeAcquisitionMethodWithLibrary(m,target,lib);if e!=nil{fmt.Printf("ACQ_METHOD_VERIFY candidate=%s stage=execution depth=%d accepted=false reason=%q\n",m.ID,depth,e.Error());return MethodEvaluation{Candidate:m,Reason:e.Error()}};base,e:=(UniversalMechanismSearch{}).SearchMechanisms(target,target.ResourceLimits);if e!=nil{fmt.Printf("ACQ_METHOD_VERIFY candidate=%s stage=baseline-search depth=%d accepted=false reason=%q\n",m.ID,depth,e.Error());return MethodEvaluation{Candidate:m,Reason:e.Error()}};changed:=!sameCandidateState(base,cs);if !changed{fmt.Printf("ACQ_METHOD_VERIFY candidate=%s stage=future-trace depth=%d accepted=false reason=%q\n",m.ID,depth,"procedure produced no observable future search change");return MethodEvaluation{Candidate:m,Reason:"procedure produced no observable future search change"}};buildFailures:=0;hiddenMisses:=0;regressionMisses:=0;for _,c:=range cs{p,e:=((UniversalProgramBuilder{MaxSynthesisExpansions: AdaptiveUniversalSynthesisMaxExpansions})).Build(c,target);if e!=nil{buildFailures++;continue};prog:=pArtifactProgram(p.Artifact);if !programFits(prog,hidden){hiddenMisses++;continue};if len(baseline)>0&&!programFits(prog,baseline){regressionMisses++;continue};fmt.Printf("ACQ_METHOD_VERIFY candidate=%s stage=independent-verification depth=%d accepted=true build_failures=%d hidden_misses=%d regression_misses=%d\n",m.ID,depth,buildFailures,hiddenMisses,regressionMisses);return MethodEvaluation{Candidate:m,Verified:true,Gain:1,Cost:c.Resources,Transfer:true,Regression:true,LeakFree:true,FutureTraceChanged:true,Reason:"independent hidden and regression cases passed with future search trace changed"}};fmt.Printf("ACQ_METHOD_VERIFY candidate=%s stage=independent-verification depth=%d accepted=false build_failures=%d hidden_misses=%d regression_misses=%d reason=%q\n",m.ID,depth,buildFailures,hiddenMisses,regressionMisses,"no executable candidate verified");return MethodEvaluation{Candidate:m,Reason:"no executable candidate verified"}}
func verifyMethodCandidate(m AcquisitionMethodArtifact,target CapabilitySpecification,hidden,baseline []ProgramTestCase)MethodEvaluation{return verifyMethodCandidateWithLibrary(m,target,hidden,baseline,nil)}
func verifyMethodCandidateWithContext(ctx context.Context,m AcquisitionMethodArtifact,target CapabilitySpecification,hidden,baseline []ProgramTestCase,lib *AbstractionLibrary)MethodEvaluation{
	if ctx == nil { ctx = context.Background() }
	if err := ctx.Err(); err != nil { return MethodEvaluation{Candidate:m,Reason:err.Error()} }
	p,e:=decodeAcquisitionProcedure(m.Procedure);if e!=nil{return MethodEvaluation{Candidate:m,Reason:e.Error()}}
	depth:=len(p.Steps)
	cs,e:=executeAcquisitionMethodWithLibrary(m,target,lib);if e!=nil{return MethodEvaluation{Candidate:m,Reason:e.Error()}}
	base,e:=(UniversalMechanismSearch{}).SearchMechanisms(target,target.ResourceLimits);if e!=nil{return MethodEvaluation{Candidate:m,Reason:e.Error()}}
	if sameCandidateState(base,cs){return MethodEvaluation{Candidate:m,Reason:"procedure produced no observable future search change"}}
	buildFailures:=0;hiddenMisses:=0;regressionMisses:=0
	for _,c:=range cs{
		if err:=ctx.Err();err!=nil{return MethodEvaluation{Candidate:m,Reason:err.Error()}}
		p,e:=((UniversalProgramBuilder{MaxSynthesisExpansions: AdaptiveUniversalSynthesisMaxExpansions})).BuildWithContext(ctx,c,target)
		if e!=nil{if ctx.Err()!=nil{return MethodEvaluation{Candidate:m,Reason:ctx.Err().Error()}};buildFailures++;continue}
		prog:=pArtifactProgram(p.Artifact)
		if !programFits(prog,hidden){hiddenMisses++;continue}
		if len(baseline)>0&&!programFits(prog,baseline){regressionMisses++;continue}
		return MethodEvaluation{Candidate:m,Verified:true,Gain:1,Cost:c.Resources,Transfer:true,Regression:true,LeakFree:true,FutureTraceChanged:true,Reason:"independent hidden and regression cases passed with future search trace changed"}
	}
	return MethodEvaluation{Candidate:m,Reason:fmt.Sprintf("no executable candidate verified; build_failures=%d hidden_misses=%d regression_misses=%d depth=%d",buildFailures,hiddenMisses,regressionMisses,depth)}
}

func pArtifactProgram(artifact string)UniversalProgram{var p UniversalProgram;_ = unmarshalJSON([]byte(artifact),&p);return p}
func selectMethod(evals []MethodEvaluation,history []AcquisitionExperience)(MethodEvaluation,error){if len(evals)==0{return MethodEvaluation{},errors.New("no method evaluations")};scores:=map[string]float64{};for _,h:=range history{if h.Verified{scores[h.Method]+=1/float64(h.SearchAttempts+1)}else{scores[h.Method]-=.25}};for i:=range evals{if !evals[i].Verified||!evals[i].Regression||!evals[i].LeakFree||!evals[i].FutureTraceChanged{continue};scores[evals[i].Candidate.Name]+=evals[i].Gain/(1+evals[i].Cost.Compute+evals[i].Cost.ExperimentBudget)};order:=append([]MethodEvaluation(nil),evals...);sort.SliceStable(order,func(i,j int)bool{return scores[order[i].Candidate.Name]>scores[order[j].Candidate.Name]});for _,e:=range order{if e.Verified&&e.Regression&&e.LeakFree&&e.FutureTraceChanged{return e,nil}};return MethodEvaluation{},errors.New("all acquisition-method candidates rejected")}
func AutonomousMethodImprovementWithLibrary(t AcquisitionTelemetry,spec CapabilitySpecification,hidden,regression []ProgramTestCase,history []AcquisitionExperience,lib *AbstractionLibrary)(AcquisitionMethodArtifact,BottleneckDiagnosis,[]MethodEvaluation,error){return AutonomousMethodImprovementWithLibraryDepth(t,spec,hidden,regression,history,lib,defaultAcquisitionProcedureMaxSteps)}

func AutonomousMethodImprovementWithLibraryDepth(t AcquisitionTelemetry,spec CapabilitySpecification,hidden,regression []ProgramTestCase,history []AcquisitionExperience,lib *AbstractionLibrary,maxSteps int)(AcquisitionMethodArtifact,BottleneckDiagnosis,[]MethodEvaluation,error){d:=DiagnoseAcquisitionTelemetry(t);cands:=AutonomousMethodCandidatesWithLibraryDepth(d,spec,spec.ResourceLimits,lib,maxSteps);evals:=make([]MethodEvaluation,0,len(cands));for i,c:=range cands{fmt.Printf("ACQ_METHOD_EVAL_ENTER index=%d total=%d candidate=%s\n",i,len(cands),c.Artifact.ID);evals=append(evals,verifyMethodCandidateWithLibrary(c.Artifact,spec,hidden,regression,lib))};verified:=0;reasonCounts:=map[string]int{};for _,e:=range evals{if e.Verified{verified++};reasonCounts[e.Reason]++};fmt.Printf("ACQ_METHOD_EVAL_SUMMARY candidates=%d evaluations=%d verified=%d reason_counts=%v\n",len(cands),len(evals),verified,reasonCounts);winner,err:=selectMethod(evals,history);if err!=nil{return AcquisitionMethodArtifact{},d,evals,err};winner.Candidate.Performance.Attempts++;winner.Candidate.Performance.Verified++;winner.Candidate.Performance.MeanGain=winner.Gain;winner.Candidate.TransferEvidence=append(winner.Candidate.TransferEvidence,"independent-heldout-transfer");return winner.Candidate,d,evals,nil}
func AutonomousMethodImprovement(t AcquisitionTelemetry,spec CapabilitySpecification,hidden,regression []ProgramTestCase,history []AcquisitionExperience)(AcquisitionMethodArtifact,BottleneckDiagnosis,[]MethodEvaluation,error){return AutonomousMethodImprovementWithLibrary(t,spec,hidden,regression,history,nil)}

func AutonomousMethodImprovementDepth(t AcquisitionTelemetry,spec CapabilitySpecification,hidden,regression []ProgramTestCase,history []AcquisitionExperience,maxSteps int)(AcquisitionMethodArtifact,BottleneckDiagnosis,[]MethodEvaluation,error){return AutonomousMethodImprovementWithLibraryDepth(t,spec,hidden,regression,history,nil,maxSteps)}
func methodTrace(m AcquisitionMethodArtifact,before,after []string)string{return fmt.Sprintf("method=%s procedure=%s before=%v after=%v",m.Name,m.Procedure,before,after)}
func methodInputOutputExample(in,out int)ProgramTestCase{return ProgramTestCase{Input:map[string]string{"x":strconv.Itoa(in)},Expected:map[string]string{"y":strconv.Itoa(out)}}}
