package ace

import("errors";"fmt";"sort";"strconv")
type AcquisitionMethodArtifact struct{ID string;Name string;Preconditions []string;ExpectedStrengths []string;ExpectedFailureModes []string;InputCapability CapabilitySpecification;Procedure string;RepresentationPolicy string;CandidatePolicy string;VerificationPolicy string;Resources ResourceVector;Provenance Provenance;Dependencies []string;Performance MethodPerformance;RegressionConstraints []string;TransferEvidence []string;Artifact string}
type MethodPerformance struct{Attempts,Verified,Failures int;MeanCost,MeanGain float64;TransferWins,Generalization int}
type AcquisitionTelemetry struct{TaskID string;TaskStructure []string;KnownExamples,CandidateCount int;CandidateFailures []string;Counterexamples int;Representation []string;SearchPath []string;VerificationOutcomes []string;Cost ResourceVector}
type BottleneckClass string
const(BottleneckRepresentation BottleneckClass="representation-insufficiency";BottleneckSearchSpace BottleneckClass="search-space-insufficiency";BottleneckSearchOrder BottleneckClass="search-order-inefficiency";BottleneckDecomposition BottleneckClass="missing-decomposition";BottleneckAbstraction BottleneckClass="missing-reusable-abstraction";BottleneckVerification BottleneckClass="weak-verification";BottleneckCounterexample BottleneckClass="weak-counterexample-generation";BottleneckMethodChoice BottleneckClass="poor-method-selection";BottleneckUnknown BottleneckClass="unknown")
type BottleneckDiagnosis struct{Class BottleneckClass;Reason string;Confidence float64;Evidence []string}
type MethodCandidate struct{Artifact AcquisitionMethodArtifact;Score float64}
type MethodEvaluation struct{Candidate AcquisitionMethodArtifact;Verified bool;Gain float64;Cost ResourceVector;Transfer,Regression,LeakFree bool;Reason string}
func DiagnoseBottleneck(t AcquisitionTelemetry)BottleneckDiagnosis{if t.CandidateCount==0{return BottleneckDiagnosis{Class:BottleneckSearchSpace,Reason:"no candidates reached verification",Confidence:.95,Evidence:[]string{"candidate-count=0"}}};failed:=false;for _,f:=range t.CandidateFailures{if f!=""{failed=true;break}};if t.Counterexamples>0&&failed{return BottleneckDiagnosis{Class:BottleneckSearchSpace,Reason:"independent counterexamples rejected the available search family",Confidence:.85,Evidence:append([]string(nil),t.CandidateFailures...)}};if len(t.SearchPath)>t.CandidateCount*4{return BottleneckDiagnosis{Class:BottleneckSearchOrder,Reason:"search expanded substantially relative to candidates tested",Confidence:.7,Evidence:[]string{fmt.Sprintf("search-path=%d",len(t.SearchPath))}}};if len(t.Representation)==0{return BottleneckDiagnosis{Class:BottleneckRepresentation,Reason:"episode has no stable representation trace",Confidence:.65,Evidence:[]string{"representation-trace-empty"}}};if len(t.VerificationOutcomes)==0{return BottleneckDiagnosis{Class:BottleneckVerification,Reason:"no independent verification outcome was recorded",Confidence:.9,Evidence:[]string{"verification-trace-empty"}}};return BottleneckDiagnosis{Class:BottleneckUnknown,Reason:"telemetry does not discriminate a bottleneck",Confidence:.2}}
func AutonomousMethodCandidatesWithLibrary(d BottleneckDiagnosis,spec CapabilitySpecification,budget ResourceVector,lib *AbstractionLibrary)[]MethodCandidate{_ = d;procedures:=EnumerateAcquisitionProceduresWithLibrary(1,lib);out:=make([]MethodCandidate,0,len(procedures));for _,p:=range procedures{artifact,e:=p.Marshal();if e!=nil{continue};sig:=procedureSignature(p);m:=AcquisitionMethodArtifact{ID:Hash([]any{"acquired-search-procedure",sig,spec.ID}),Name:"acquired-procedure:"+sig,Preconditions:[]string{"independent behavioral evidence","within resource budget"},ExpectedStrengths:[]string{"generic candidate-stream transformation"},ExpectedFailureModes:[]string{"insufficient behavioral evidence","resource exhaustion"},InputCapability:spec,Procedure:artifact,RepresentationPolicy:"unchanged-unless-evidence-requires-revision",CandidatePolicy:"executable-procedure-enumeration",VerificationPolicy:"independent-heldout-regression-transfer",Resources:budget,Dependencies:abstractionDependencies(p),RegressionConstraints:[]string{"previous verified capabilities remain valid"},Provenance:Prov("blind-procedure-synthesis",spec.ID,"enumerate-generic-stream-program",p),Artifact:artifact};out=append(out,MethodCandidate{Artifact:m})};return out}
func AutonomousMethodCandidates(d BottleneckDiagnosis,spec CapabilitySpecification,budget ResourceVector)[]MethodCandidate{return AutonomousMethodCandidatesWithLibrary(d,spec,budget,nil)}
func executeAcquisitionMethodWithLibrary(m AcquisitionMethodArtifact,spec CapabilitySpecification,lib *AbstractionLibrary)([]ArchitectureCandidate,error){p,e:=decodeAcquisitionProcedure(m.Artifact);if e!=nil{return nil,e};cs,e:=(UniversalMechanismSearch{}).SearchMechanisms(spec,spec.ResourceLimits);if e!=nil{return nil,e};return executeSearchProcedureWithLibrary(p,cs,lib)}
func executeAcquisitionMethod(m AcquisitionMethodArtifact,spec CapabilitySpecification)([]ArchitectureCandidate,error){return executeAcquisitionMethodWithLibrary(m,spec,nil)}
func verifyMethodCandidateWithLibrary(m AcquisitionMethodArtifact,target CapabilitySpecification,hidden,baseline []ProgramTestCase,lib *AbstractionLibrary)MethodEvaluation{cs,e:=executeAcquisitionMethodWithLibrary(m,target,lib);if e!=nil{return MethodEvaluation{Candidate:m,Reason:e.Error()}};best:=MethodEvaluation{Candidate:m,Reason:"no executable candidate verified"};for _,c:=range cs{p,e:=(UniversalProgramBuilder{}).Build(c,target);if e!=nil{continue};prog:=pArtifactProgram(p.Artifact);if !programFits(prog,hidden){continue};if len(baseline)>0&&!programFits(prog,baseline){continue};best=MethodEvaluation{Candidate:m,Verified:true,Gain:1,Cost:c.Resources,Transfer:true,Regression:true,LeakFree:true,Reason:"independent hidden and regression cases passed"};break};return best}
func verifyMethodCandidate(m AcquisitionMethodArtifact,target CapabilitySpecification,hidden,baseline []ProgramTestCase)MethodEvaluation{return verifyMethodCandidateWithLibrary(m,target,hidden,baseline,nil)}
func pArtifactProgram(artifact string)UniversalProgram{var p UniversalProgram;_ = unmarshalJSON([]byte(artifact),&p);return p}
func selectMethod(evals []MethodEvaluation,history []AcquisitionExperience)(MethodEvaluation,error){if len(evals)==0{return MethodEvaluation{},errors.New("no method evaluations")};scores:=map[string]float64{};for _,h:=range history{if h.Verified{scores[h.Method]+=1/float64(h.SearchAttempts+1)}else{scores[h.Method]-=.25}};for i:=range evals{if !evals[i].Verified||!evals[i].Regression||!evals[i].LeakFree{continue};scores[evals[i].Candidate.Name]+=evals[i].Gain/(1+evals[i].Cost.Compute+evals[i].Cost.ExperimentBudget)};order:=append([]MethodEvaluation(nil),evals...);sort.SliceStable(order,func(i,j int)bool{return scores[order[i].Candidate.Name]>scores[order[j].Candidate.Name]});for _,e:=range order{if e.Verified&&e.Regression&&e.LeakFree{return e,nil}};return MethodEvaluation{},errors.New("all acquisition-method candidates rejected")}
func AutonomousMethodImprovementWithLibrary(t AcquisitionTelemetry,spec CapabilitySpecification,hidden,regression []ProgramTestCase,history []AcquisitionExperience,lib *AbstractionLibrary)(AcquisitionMethodArtifact,BottleneckDiagnosis,[]MethodEvaluation,error){d:=DiagnoseBottleneck(t);cands:=AutonomousMethodCandidatesWithLibrary(d,spec,spec.ResourceLimits,lib);evals:=make([]MethodEvaluation,0,len(cands));for _,c:=range cands{evals=append(evals,verifyMethodCandidateWithLibrary(c.Artifact,spec,hidden,regression,lib))};winner,err:=selectMethod(evals,history);if err!=nil{return AcquisitionMethodArtifact{},d,evals,err};winner.Candidate.Performance.Attempts++;winner.Candidate.Performance.Verified++;winner.Candidate.Performance.MeanGain=winner.Gain;winner.Candidate.TransferEvidence=append(winner.Candidate.TransferEvidence,"independent-heldout-transfer");return winner.Candidate,d,evals,nil}
func AutonomousMethodImprovement(t AcquisitionTelemetry,spec CapabilitySpecification,hidden,regression []ProgramTestCase,history []AcquisitionExperience)(AcquisitionMethodArtifact,BottleneckDiagnosis,[]MethodEvaluation,error){return AutonomousMethodImprovementWithLibrary(t,spec,hidden,regression,history,nil)}
func methodTrace(m AcquisitionMethodArtifact,before,after []string)string{return fmt.Sprintf("method=%s procedure=%s before=%v after=%v",m.Name,m.Procedure,before,after)}
func methodInputOutputExample(in,out int)ProgramTestCase{return ProgramTestCase{Input:map[string]string{"x":strconv.Itoa(in)},Expected:map[string]string{"y":strconv.Itoa(out)}}}
