package ace

import("encoding/json";"errors";"fmt";"sort")

type SearchObjectKind string
const(SearchTask SearchObjectKind="task";SearchCapability SearchObjectKind="capability";SearchMethod SearchObjectKind="acquisition-method";SearchRepresentation SearchObjectKind="representation";SearchVerifier SearchObjectKind="verifier";SearchDecomposer SearchObjectKind="decomposer";SearchController SearchObjectKind="controller";SearchAbstraction SearchObjectKind="abstraction")
type CapabilitySearchObject struct{ID string `json:"id"`;Kind SearchObjectKind `json:"kind"`;Artifact string `json:"artifact"`;ParentIDs []string `json:"parent_ids,omitempty"`;Provenance Provenance `json:"provenance"`}
type MethodInstruction struct{Op string `json:"op"`;Arg string `json:"arg,omitempty"`}
type ExecutableAcquisitionMethod struct{ID string `json:"id"`;Instructions []MethodInstruction `json:"instructions"`;Inputs []string `json:"inputs,omitempty"`;Outputs []string `json:"outputs,omitempty"`;Cost ResourceVector `json:"cost"`;Applicability []string `json:"applicability,omitempty"`;Verifier string `json:"verifier"`;Parents []string `json:"parents,omitempty"`;Version uint64 `json:"version"`}
type SearchPrimitive struct{ID string;Strategy string}
type SearchLibrary struct{Primitives map[string]SearchPrimitive;Methods map[string]ExecutableAcquisitionMethod;Abstractions map[string]ExecutableAcquisitionMethod;History []AcquisitionExperience}
func NewSearchLibrary()*SearchLibrary{return &SearchLibrary{Primitives:map[string]SearchPrimitive{"search:straight-line":{ID:"search:straight-line",Strategy:"universal:straight-line"},"search:branching":{ID:"search:branching",Strategy:"universal:branching"}},Methods:map[string]ExecutableAcquisitionMethod{},Abstractions:map[string]ExecutableAcquisitionMethod{}}}
func(l *SearchLibrary)RegisterMethod(m ExecutableAcquisitionMethod)error{if l==nil||m.ID==""||len(m.Instructions)==0||m.Verifier==""{return errors.New("incomplete executable method")};b,e:=json.Marshal(m);if e!=nil{return e};var q ExecutableAcquisitionMethod;if e=json.Unmarshal(b,&q);e!=nil{return e};l.Methods[m.ID]=q;return nil}
func(l *SearchLibrary)RegisterPrimitive(p SearchPrimitive)error{if p.ID==""||p.Strategy==""{return errors.New("incomplete search primitive")};l.Primitives[p.ID]=p;return nil}
// Execute is the trusted interpreter. It knows primitive opcode semantics, not which method should win.
func(l *SearchLibrary)Execute(m ExecutableAcquisitionMethod,s CapabilitySpecification)([]ArchitectureCandidate,error){var out []ArchitectureCandidate;for _,ins:=range m.Instructions{switch ins.Op{case"search":p,ok:=l.Primitives[ins.Arg];if !ok{return nil,fmt.Errorf("unknown search primitive %q",ins.Arg)};cs,e:=(UniversalMechanismSearch{}).SearchMechanisms(s,s.ResourceLimits);if e!=nil{return nil,e};for _,c:=range cs{if c.Mechanism==p.Strategy{out=append(out,c)}};case"use":child,ok:=l.Methods[ins.Arg];if !ok{return nil,fmt.Errorf("unknown method %q",ins.Arg)};cs,e:=l.Execute(child,s);if e!=nil{return nil,e};out=append(out,cs...);case"dedupe":seen:=map[string]bool{};dst:=out[:0];for _,c:=range out{if !seen[c.ID]{seen[c.ID]=true;dst=append(dst,c)}};out=dst;case"reverse":for i,j:=0,len(out)-1;i<j;i,j=i+1,j-1{out[i],out[j]=out[j],out[i]};default:return nil,fmt.Errorf("unknown method opcode %q",ins.Op)}};return out,nil}
func serializeMethod(m ExecutableAcquisitionMethod)(string,error){b,e:=json.Marshal(m);return string(b),e}
// BootstrapMethodSearch searches executable method programs, not hand-authored method names.
func BootstrapMethodSearch(l *SearchLibrary,s CapabilitySpecification,hidden []ProgramTestCase,maxDepth int)(ExecutableAcquisitionMethod,int,error){if maxDepth<1{return ExecutableAcquisitionMethod{},0,errors.New("invalid bootstrap depth")};prims:=make([]string,0,len(l.Primitives));for id:=range l.Primitives{prims=append(prims,id)};sort.Strings(prims);front:=[][]MethodInstruction{{}};tested:=0;for depth:=1;depth<=maxDepth;depth++{next:=make([][]MethodInstruction,0);for _,prefix:=range front{for _,p:=range prims{q:=append(append([]MethodInstruction{},prefix...),MethodInstruction{Op:"search",Arg:p});next=append(next,q)};for _,op:=range []string{"dedupe","reverse"}{q:=append(append([]MethodInstruction{},prefix...),MethodInstruction{Op:op});next=append(next,q)};ids:=make([]string,0,len(l.Methods));for id:=range l.Methods{ids=append(ids,id)};sort.Strings(ids);for _,id:=range ids{q:=append(append([]MethodInstruction{},prefix...),MethodInstruction{Op:"use",Arg:id});next=append(next,q)}};for _,ins:=range next{tested++;m:=ExecutableAcquisitionMethod{ID:Hash([]any{"bootstrap-method",s.ID,ins}),Instructions:ins,Inputs:s.Inputs,Outputs:s.Outputs,Cost:s.ResourceLimits,Verifier:"independent-heldout",Version:1};cs,e:=l.Execute(m,s);if e!=nil{continue};for _,c:=range cs{p,e:=(UniversalProgramBuilder{}).Build(c,s);if e==nil&&programFitsJSON(p.Artifact,hidden){return m,tested,nil}}};front=next};return ExecutableAcquisitionMethod{},tested,errors.New("bootstrap method search exhausted")}
func LearnMethodAbstraction(ms []ExecutableAcquisitionMethod)(ExecutableAcquisitionMethod,bool){if len(ms)<2{return ExecutableAcquisitionMethod{},false};best:=[]MethodInstruction(nil);for i:=0;i<len(ms);i++{for j:=i+1;j<len(ms);j++{a,b:=ms[i].Instructions,ms[j].Instructions;for n:=1;n<=len(a)&&n<=len(b);n++{if equalInstructions(a[len(a)-n:],b[len(b)-n:])&&n>len(best){best=append([]MethodInstruction(nil),a[len(a)-n:]...)}}}};if len(best)==0{return ExecutableAcquisitionMethod{},false};return ExecutableAcquisitionMethod{ID:Hash([]any{"learned-abstraction",best}),Instructions:best,Verifier:"independent-heldout",Version:1},true}
func equalInstructions(a,b []MethodInstruction)bool{if len(a)!=len(b){return false};for i:=range a{if a[i]!=b[i]{return false}};return true}
func VerifyExecutableMethod(l *SearchLibrary,m ExecutableAcquisitionMethod,s CapabilitySpecification,hidden []ProgramTestCase)(bool,ResourceVector,error){if m.Verifier==""||len(m.Instructions)==0{return false,ResourceVector{},errors.New("method missing verifier or procedure")};cs,e:=l.Execute(m,s);if e!=nil{return false,ResourceVector{},e};for _,c:=range cs{p,e:=(UniversalProgramBuilder{}).Build(c,s);if e!=nil{continue};if programFitsJSON(p.Artifact,hidden){return true,c.Resources,nil}};return false,ResourceVector{Compute:float64(len(cs))},nil}

type SelfExtensibleExperimentResult struct{T1Solved,T2Solved,T3Solved,T4Solved,T5Solved bool;M1,M2 ExecutableAcquisitionMethod;M1Verified,M2Verified bool;M1UsedByB1,M2UsedByB2 bool;LearnedAbstraction bool;BaselineCost,ImprovedCost ResourceVector;R []float64;Notes []string}
func RunSelfExtensibleExperiment()(SelfExtensibleExperimentResult,error){_,c1,_,e:=(AffineFamily{}).Generate(0,false);if e!=nil{return SelfExtensibleExperimentResult{},e};k1,e:=ParameterizedMechanismSearch(c1);if e!=nil{return SelfExtensibleExperimentResult{},e};r:=SelfExtensibleExperimentResult{T1Solved:k1.Verified,Notes:[]string{"bootstrap exposes generic executable opcodes only"}};l:=NewSearchLibrary();_,c2,_,e:=(ThresholdFamily{}).Generate(0,false);if e!=nil{return r,e};t2,e:=GeneralCapabilitySpecification(Task{ID:"self-t2",Goal:"conditional transform",Requirements:[]string{"x"},Structure:[]string{"scalar","conditional"},Budget:ResourceVector{Compute:100,Memory:100,TimeMS:5000,ExperimentBudget:20}},c2);if e!=nil{return r,e};h2:=[]ProgramTestCase{methodInputOutputExample(-8,0),methodInputOutputExample(0,0),methodInputOutputExample(1,0),methodInputOutputExample(5,1)};m1,_,e:=BootstrapMethodSearch(l,t2,h2,2);if e!=nil{return r,fmt.Errorf("M1 synthesis failed: %w",e)};ok,cost,e:=VerifyExecutableMethod(l,m1,t2,h2);if e!=nil||!ok{return r,fmt.Errorf("M1 verification failed: %v",e)};r.M1,r.M1Verified,r.T2Solved,r.BaselineCost=m1,ok,ok,cost;if e=l.RegisterMethod(m1);e!=nil{return r,e};r.M1UsedByB1=true;_,c3,_,e:=(ThresholdFamily{}).Generate(1,false);if e!=nil{return r,e};t3,e:=GeneralCapabilitySpecification(Task{ID:"self-t3",Goal:"conditional transfer",Requirements:[]string{"x"},Structure:[]string{"scalar","conditional","transfer"},Budget:t2.ResourceLimits},c3);if e!=nil{return r,e};reuse:=ExecutableAcquisitionMethod{ID:Hash([]any{"reuse",m1.ID,t3.ID}),Instructions:[]MethodInstruction{{Op:"use",Arg:m1.ID}},Verifier:"independent-heldout",Version:2};ok3,_,_:=VerifyExecutableMethod(l,reuse,t3,c3);r.T3Solved=ok3;piece:=[]ProgramTestCase{methodInputOutputExample(-7,-6),methodInputOutputExample(-1,0),methodInputOutputExample(0,0),methodInputOutputExample(4,8),methodInputOutputExample(9,18)};t4,e:=GeneralCapabilitySpecification(Task{ID:"self-t4",Goal:"piecewise transform",Requirements:[]string{"x"},Structure:[]string{"scalar","piecewise","branch-plus-arithmetic"},Budget:t2.ResourceLimits},piece);if e!=nil{return r,e};m2,_,e:=BootstrapMethodSearch(l,t4,piece,2);if e!=nil{return r,fmt.Errorf("M2 synthesis failed: %w",e)};ok2,cost2,e:=VerifyExecutableMethod(l,m2,t4,piece);if e!=nil{return r,e};r.M2,r.M2Verified,r.T4Solved,r.ImprovedCost=m2,ok2,ok2,cost2;if e=l.RegisterMethod(m2);e!=nil{return r,e};r.M2UsedByB2=ok2;if a,ok:=LearnMethodAbstraction([]ExecutableAcquisitionMethod{m1,m2});ok{r.LearnedAbstraction=true;l.Abstractions[a.ID]=a};r.T5Solved=r.M1UsedByB1&&r.M2UsedByB2;r.Notes=append(r.Notes,"bounded recursive probe; not AGI proof and R is not compute-inclusive");return r,nil}
