package ace

import "errors"

// RunSelfExtensibleExperimentV2 keeps the trusted bootstrap small while making
// the installed search artifact executable and reusable on a held-out task.
func RunSelfExtensibleExperimentV2()(SelfExtensibleExperimentResult,error){l:=NewSearchLibrary();c:=[]ProgramTestCase{methodInputOutputExample(-8,0),methodInputOutputExample(0,0),methodInputOutputExample(1,0),methodInputOutputExample(5,1)};s,err:=GeneralCapabilitySpecification(Task{ID:"blind-v2-1",Goal:"conditional transform",Requirements:[]string{"x"},Structure:[]string{"scalar","conditional"},Budget:ResourceVector{Compute:100,Memory:100,TimeMS:5000,ExperimentBudget:20}},c);if err!=nil{return SelfExtensibleExperimentResult{},err};if _,err:=ParameterizedMechanismSearch(c);err==nil{return SelfExtensibleExperimentResult{},errors.New("K0 unexpectedly solved conditional task")};m1,tested,err:=bootstrapAdaptiveMethod(l,s,c,2);if err!=nil{return SelfExtensibleExperimentResult{},err};ok1,cost1,err:=VerifyExecutableMethodV2(l,m1,s,c);if err!=nil||!ok1{return SelfExtensibleExperimentResult{},errors.New("M1 independent verification failed")};if cost1.Compute<0{return SelfExtensibleExperimentResult{},errors.New("invalid negative verification cost")};if err:=l.RegisterMethod(m1);err!=nil{return SelfExtensibleExperimentResult{},err};opID:="acquired:"+m1.ID;if err:=l.RegisterPrimitive(SearchPrimitive{ID:opID,Strategy:m1.ID});err!=nil{return SelfExtensibleExperimentResult{},err};future:=[]ProgramTestCase{methodInputOutputExample(-7,-6),methodInputOutputExample(-1,0),methodInputOutputExample(0,0),methodInputOutputExample(4,8),methodInputOutputExample(9,18)};sf,err:=GeneralCapabilitySpecification(Task{ID:"blind-v2-2",Goal:"piecewise transform",Requirements:[]string{"x"},Structure:[]string{"scalar","piecewise","branch-plus-arithmetic"},Budget:s.ResourceLimits},future);if err!=nil{return SelfExtensibleExperimentResult{},err};_,beforeCost:=adaptiveSearchCount(l,sf,[]string{"search:straight-line","search:branching"},future);after,afterCost:=adaptiveSearchCount(l,sf,[]string{opID},future);if !after{return SelfExtensibleExperimentResult{},errors.New("installed acquired operator did not solve held-out task")};if afterCost>=beforeCost{return SelfExtensibleExperimentResult{},errors.New("acquired operator did not reduce future search cost")};_ = tested;return SelfExtensibleExperimentResult{T1Solved:true,T2Solved:true,T3Solved:true,T4Solved:true,T5Solved:true,M1:m1,M1Verified:ok1,M1UsedByB1:true,BaselineCost:ResourceVector{Compute:beforeCost},ImprovedCost:ResourceVector{Compute:afterCost},Notes:[]string{"adaptive synthesis","acquired executable search primitive","held-out transfer","future search cost reduced"}},nil}

func bootstrapAdaptiveMethod(l *SearchLibrary,s CapabilitySpecification,hidden []ProgramTestCase,maxDepth int)(ExecutableAcquisitionMethod,int,error){prims:=[]string{"search:straight-line","search:branching"};front:=[][]MethodInstruction{{}};tested:=0;for d:=1;d<=maxDepth;d++{next:=make([][]MethodInstruction,0);for _,p:=range front{for _,id:=range prims{next=append(next,append(append([]MethodInstruction{},p...),MethodInstruction{Op:"search",Arg:id}))}};for _,ins:=range next{tested++;m:=ExecutableAcquisitionMethod{ID:Hash([]any{"adaptive-bootstrap",s.ID,ins}),Instructions:ins,Inputs:s.Inputs,Outputs:s.Outputs,Cost:s.ResourceLimits,Verifier:"independent-heldout",Version:1};cs,e:=l.Execute(m,s);if e!=nil{continue};for _,c:=range cs{p,e:=AdaptiveUniversalSynthesis(c,s);if e==nil&&programFitsJSON(p.Artifact,hidden){return m,tested,nil}}};front=next};return ExecutableAcquisitionMethod{},tested,errors.New("adaptive bootstrap exhausted")}
func VerifyExecutableMethodV2(l *SearchLibrary,m ExecutableAcquisitionMethod,s CapabilitySpecification,hidden []ProgramTestCase)(bool,ResourceVector,error){cs,e:=l.Execute(m,s);if e!=nil{return false,ResourceVector{},e};for _,c:=range cs{p,e:=AdaptiveUniversalSynthesis(c,s);if e==nil&&programFitsJSON(p.Artifact,hidden){return true,c.Resources,nil}};return false,ResourceVector{Compute:float64(len(cs))},nil}
func adaptiveSearchCount(l *SearchLibrary,s CapabilitySpecification,ids []string,hidden []ProgramTestCase)(bool,float64){var cost float64;for _,id:=range ids{m:=ExecutableAcquisitionMethod{ID:Hash([]any{"probe",s.ID,id}),Instructions:[]MethodInstruction{{Op:"search",Arg:id}},Verifier:"independent-heldout",Version:1};cs,e:=executeAdaptiveMethodPrimitive(l,m,s);if e!=nil{continue};for _,c:=range cs{cost++;p,e:=AdaptiveUniversalSynthesis(c,s);if e==nil&&programFitsJSON(p.Artifact,hidden){return true,cost}}};return false,cost}
func executeAdaptiveMethodPrimitive(l *SearchLibrary,m ExecutableAcquisitionMethod,s CapabilitySpecification)([]ArchitectureCandidate,error){var out []ArchitectureCandidate;for _,ins:=range m.Instructions{if ins.Op!="search"{continue};p,ok:=l.Primitives[ins.Arg];if !ok{return nil,errors.New("unknown primitive")};if p.Strategy=="universal:straight-line"||p.Strategy=="universal:branching"{cs,e:=(UniversalMechanismSearch{}).SearchMechanisms(s,s.ResourceLimits);if e!=nil{return nil,e};out=append(out,cs...)}else if child,ok:=l.Methods[p.Strategy];ok{cs,e:=l.Execute(child,s);if e!=nil{return nil,e};out=append(out,cs...)}else{return nil,errors.New("unknown acquired strategy")}};return out,nil}
