package main
import("bufio";"crypto/sha256";"encoding/hex";"encoding/json";"fmt";"os";"sort")
type Obs struct{State map[string]string `json:"state"`; Available []string `json:"available_actions"`; LastAction any `json:"last_action"`; LastResult any `json:"last_result"`; Terminated bool `json:"terminated"`}
type Atom struct{P string `json:"predicate"`; A []string `json:"args"`}; type Rule struct{Atoms []Atom `json:"atoms"`; Consequence string `json:"consequence"`}
type Cost struct{Attempts int `json:"attempts"`; Terminal string `json:"terminal"`}; type Fixture struct{Seed uint64 `json:"seed"`; History []Obs `json:"history"`; Candidate Rule `json:"candidate"`; Binding map[string]string `json:"binding"`; NextAction string `json:"next_action"`; Cost Cost `json:"cost"`; Attribution map[string]any `json:"attribution"`; NoveltyA []map[string]any `json:"novelty_a"`; NoveltyB []map[string]any `json:"novelty_b"`}
func enc(v any)[]byte{b,_:=json.Marshal(v);return b};func digest(b []byte)string{h:=sha256.Sum256(b);return hex.EncodeToString(h[:])}
func tok(ns string,seed,idx uint64)string{b:=append([]byte(ns+"\x00"),make([]byte,16)...);for i:=0;i<8;i++{b[len(ns)+1+i]=byte(seed>>(56-8*i));b[len(ns)+9+i]=byte(idx>>(56-8*i))};h:=sha256.Sum256(b);return hex.EncodeToString(h[:])[:16]}
func word(ns string,seed,c uint64)uint64{b:=append([]byte(ns+"\x00"),make([]byte,16)...);for i:=0;i<8;i++{b[len(ns)+1+i]=byte(seed>>(56-8*i));b[len(ns)+9+i]=byte(c>>(56-8*i))};h:=sha256.Sum256(b);var x uint64;for _,v:=range h[:8]{x=x<<8|uint64(v)};return x}
func ruleMap(r Rule)map[string]any{return map[string]any{"atoms":r.Atoms,"consequence":r.Consequence}}
func ruleCanon(r Rule)Rule{m:=map[string]Atom{};for _,a:=range r.Atoms{m[string(enc(a))]=a};keys:=make([]string,0,len(m));for k:=range m{keys=append(keys,k)};sort.Strings(keys);o:=make([]Atom,0,len(keys));for _,k:=range keys{o=append(o,m[k])};r.Atoms=o;return r}
func valid(r Rule)bool{if r.Consequence!="ENABLES(target)"&&r.Consequence!="NONENABLES(contrast,target)"{return false};if len(r.Atoms)<1||len(r.Atoms)>6{return false};seen:=map[string]bool{};arity:=map[string]int{"BLOCKED":1,"AVAILABLE":1,"ACTION":1,"INTERVENES":2,"BEFORE":2,"AFTER":2,"OBSERVED_EFFECT":2,"ENABLES":2,"NONENABLES":2,"SAME_LOCAL_CONTEXT":2};for _,a:=range r.Atoms{n,ok:=arity[a.P];if !ok||len(a.A)!=n{return false};for _,x:=range a.A{if x!="target"&&x!="intervention"&&x!="contrast"&&x!="context"&&x!="ENABLES(target)"&&x!="NONENABLES(contrast,target)"{return false}};k:=string(enc(a));if seen[k]{return false};seen[k]=true};return true}
type Fact struct{P string `json:"p"`;A []string `json:"a"`;At int `json:"at"`}
func facts(h []Obs)[]Fact{var out []Fact;has:=func(a []string,s string)bool{for _,v:=range a{if v==s{return true}};return false};for i,o:=range h{av:=append([]string(nil),o.Available...);sort.Strings(av);for _,x:=range av{out=append(out,Fact{"AVAILABLE",[]string{x},i})};x,ok:=o.LastAction.(string);if ok{out=append(out,Fact{"ACTION",[]string{x},i})};if i>0&&ok{prev,cur:=h[i-1].Available,o.Available;seen:=map[string]bool{};for _,t:=range append(append([]string{},prev...),cur...){if seen[t]{continue};seen[t]=true;if !has(prev,t)&&has(cur,t){out=append(out,Fact{"INTERVENES",[]string{x,t},i-1});out=append(out,Fact{"OBSERVED_EFFECT",[]string{x,"ENABLES("+t+")"},i-1})}else if !has(prev,t)&&!has(cur,t){out=append(out,Fact{"NONENABLES",[]string{x,t},i-1})}};if m,ok:=o.LastResult.(map[string]any);ok{if s,_:=m["status"].(string);s=="BLOCKED"{out=append(out,Fact{"BLOCKED",[]string{x},i})}}}};sort.Slice(out,func(i,j int)bool{return string(enc(out[i]))<string(enc(out[j]))});return out}
func applicable(r Rule,b map[string]string,fs []Fact)bool{for _,a:=range r.Atoms{args:=make([]string,len(a.A));for i,x:=range a.A{if v,ok:=b[x];ok{args[i]=v}else{args[i]=x}};ok:=false;for _,f:=range fs{if f.P==a.P&&len(f.A)==len(args){same:=true;for i:=range args{if f.A[i]!=args[i]{same=false}};if same{ok=true;break}}};if !ok{return false}};return true}
func attr(m map[string]any)string{if b,_:=m["outside_domain"].(bool);b{return "PROTOCOL_VIOLATION"};set:=map[string]bool{};if e,ok:=m["evidence"].([]any);ok{for _,x:=range e{if s,ok:=x.(string);ok{set[s]=true}}};if set["invalid"]{return "UNATTRIBUTABLE"};if set["conflict"]{return "CONFLICT"};if set["retrieval"]&&!set["prediction"]{return "RETRIEVAL_ONLY"};if set["prediction"]&&!set["intervention"]{return "PREDICTION_ONLY"};if set["coincidental"]{return "COINCIDENTAL"};for _,x:=range []string{"retrieval","prediction","intervention","consequence","verification","counterfactual"}{if !set[x]{return "UNATTRIBUTABLE"}};return "KA_TRANSFER"}
func cost(c Cost)any{if c.Terminal=="SUCCESS"||c.Terminal=="INTERACTION_CAP_EXHAUSTED"||c.Terminal=="DECISION_CUTOFF_EXHAUSTED"{return c.Attempts};return nil}
func novelty(a,b []map[string]any)float64{sa,sb:=map[string]bool{},map[string]bool{};for _,x:=range a{sa[string(enc(x))]=true};for _,x:=range b{sb[string(enc(x))]=true};u,i:=0,0;for k:=range sa{u++;if sb[k]{i++}};for k:=range sb{if !sa[k]{u++}};if u==0{return 1};return 1-float64(i)/float64(u)}
func main(){s:=bufio.NewScanner(os.Stdin);s.Scan();raw:=append([]byte(nil),s.Bytes()...);var f Fixture;var rawMap map[string]any;if json.Unmarshal(raw,&f)!=nil||json.Unmarshal(raw,&rawMap)!=nil{panic("invalid fixture")};r:=ruleCanon(f.Candidate);fs:=facts(f.History);app:=applicable(r,f.Binding,fs);var pred any;if app{pred=r.Consequence};out:=map[string]any{"input_hash":digest(enc(rawMap)),"event_ledger":f.History,"facts":fs,"candidate":ruleMap(r),"candidate_valid":valid(r),"retrieval":map[string]any{"applicable":app,"candidate":func()any{if app{return ruleMap(r)};return nil}()},"prediction":map[string]any{"consequence":pred,"valid":pred!=nil},"action":f.NextAction,"cost":cost(f.Cost),"attribution":attr(f.Attribution),"novelty":novelty(f.NoveltyA,f.NoveltyB),"task_tokens":map[string]string{"action":tok("ACTION_TOKEN",f.Seed,0),"location":tok("LOCATION_TOKEN",f.Seed,0)},"rng_probe":[]uint64{word("TASK_GENERATION",f.Seed,0),word("TASK_GENERATION",f.Seed,1),word("TASK_GENERATION",f.Seed,2),word("TASK_GENERATION",f.Seed,3)}};fmt.Println(string(enc(out)))}
